name: Assemble

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  keystore_password: ${{ secrets.KeystorePassword }}
  keystore_alias: ${{ secrets.KeystoreAlias }}
  keystore_alias_password: ${{ secrets.KeystoreAliasPassword }}

jobs:
  assemble-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Decrypt keystore file
        run: |
          gpg --quiet --batch --yes --decrypt \
              --passphrase="${{ secrets.KeystoreEncKey }}" \
              --output release.jks \
              opencamera-sensors.jks.gpg

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble release
        run: ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
